Update patch set 11
Patch Set 11:

> Patch Set 10: Code-Review+2
> 
> Dylan, I think I found the problem. AOSP master differs versus our internal master, which may account for build failures you don't see, but are reported by Treehugger. In the interest of speed, I made a few small edits on your CL to make it build on our internal master, and to verify it passes Treehugger.  Can you please check on your side if the CL works as expected?
> 
> Note: the edits still preserve attribution of you as the CL author, but unfortunately automatically changes me to the committer/uploader. Please feel free to make a minor edit of any sort to the commit message if you wish to have committer/uploader changed back to you, I realize this might be necessary attribution in your role.
> 
> Thanks again for working on fuzzing and your persistence on this CL!

Andy, I seem to be encountering a similar build error when I use your changes locally to the one treehugger experienced before your change was made. The build issue is blocking me from testing this on my side:

```
============================================
[ 42% 8/19] //frameworks/av/media/utils/fuzzers:libmediautils_fuzzer_scheduling_policy_service clang++ SchedulingPolicyServiceFuzz.cpp
FAILED: /home/dkatz/android_out/soong/.intermediates/frameworks/av/media/utils/fuzzers/libmediautils_fuzzer_scheduling_policy_service/android_arm64_armv8-a_asan_fuzzer/obj/frameworks/av/media/utils/fuzzers/SchedulingPolicyServiceFuzz.o
PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r383902b/bin/clang++ -c -Wno-enum-compare -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -Wno-null-dereference -Wno-pointer-compare -Wno-xor-used-as-pow -Wno-final-dtor-non-final-class  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wno-c99-designator -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -march=armv8-a  -target aarch64-linux-android10000 -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -fPIE -Wsign-promo -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -Isystem/core/debuggerd/include -Iframeworks/av/media/utils/fuzzers -D__LIBC_API__=10000 -D__LIBM_API__=10000 -D__LIBDL_API__=10000 -Ibionic/libc/platform -Iframeworks/av/media/libmedia/include -Iframeworks/native/libs/gui/include -Isystem/libhidl/transport/token/1.0/utils/include -Iframeworks/native/libs/binder/include -Isystem/libbase/include -Isystem/core/libcutils/include -Isystem/core/libutils/include -Isystem/core/libbacktrace/include -Isystem/core/liblog/include -Isystem/core/libsystem/include -Isystem/core/libprocessgroup/include -Isystem/libhidl/base/include -Isystem/libhidl/transport/include -Isystem/libhwbinder/include -Iexternal/fmtlib/include -I/home/dkatz/android_out/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager@1.0_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/system/libhidl/transport/manager/1.1/android.hidl.manager@1.1_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/system/libhidl/transport/manager/1.2/android.hidl.manager@1.2_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/system/libhidl/transport/base/1.0/android.hidl.base@1.0_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/hardware/interfaces/graphics/common/1.0/android.hardware.graphics.common@1.0_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/hardware/interfaces/media/1.0/android.hardware.media@1.0_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/hardware/interfaces/graphics/bufferqueue/1.0/android.hardware.graphics.bufferqueue@1.0_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/hardware/interfaces/graphics/common/1.1/android.hardware.graphics.common@1.1_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/hardware/interfaces/graphics/common/1.2/android.hardware.graphics.common@1.2_genc++_headers/gen -I/home/dkatz/android_out/soong/.intermediates/hardware/interfaces/graphics/bufferqueue/2.0/android.hardware.graphics.bufferqueue@2.0_genc++_headers/gen -Iframeworks/av/media/libstagefright/include -Iframeworks/native/headers/media_plugin -Iframeworks/native/headers/media_plugin/media/openmax -Iframeworks/av/media/libstagefright/foundation/include -Iexternal/libcxxabi/include -I/home/dkatz/android_out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_arm64_armv8-a_shared_asan_fuzzer/gen/aidl -Iframeworks/av/media/utils/include -Iexternal/libcxx/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -Wall -Wextra -Werror -Wno-c++2a-extensions -fno-omit-frame-pointer -fno-experimental-new-pass-manager -mllvm -asan-globals=0 -fsanitize=fuzzer-no-link -fno-lto -fno-sanitize-coverage=stack-depth -fno-experimental-new-pass-manager -U_FORTIFY_SOURCE -fsanitize=address,fuzzer-no-link -fno-sanitize-trap=all -fno-sanitize-recover=all -fno-sanitize-trap=address -std=gnu++17 -fno-rtti -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-string-compare -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-pessimizing-move -MD -MF /home/dkatz/android_out/soong/.intermediates/frameworks/av/media/utils/fuzzers/libmediautils_fuzzer_scheduling_policy_service/android_arm64_armv8-a_asan_fuzzer/obj/frameworks/av/media/utils/fuzzers/SchedulingPolicyServiceFuzz.o.d -o /home/dkatz/android_out/soong/.intermediates/frameworks/av/media/utils/fuzzers/libmediautils_fuzzer_scheduling_policy_service/android_arm64_armv8-a_asan_fuzzer/obj/frameworks/av/media/utils/fuzzers/SchedulingPolicyServiceFuzz.o frameworks/av/media/utils/fuzzers/SchedulingPolicyServiceFuzz.cpp
In file included from frameworks/av/media/utils/fuzzers/SchedulingPolicyServiceFuzz.cpp:17:
In file included from frameworks/native/libs/binder/include/binder/IBatteryStats.h:22:
In file included from frameworks/native/libs/binder/include/binder/IInterface.h:21:
In file included from frameworks/native/libs/binder/include/binder/Binder.h:22:
In file included from frameworks/native/libs/binder/include/binder/IBinder.h:21:
In file included from system/core/libutils/include/utils/RefBase.h:185:
system/core/libutils/include/utils/StrongPointer.h:231:11: error: cannot initialize a member subobject of type 'android::IInterface *' with an lvalue of type 'android::IBinder *'
        : m_ptr(other.m_ptr) {
          ^     ~~~~~~~~~~~
frameworks/av/media/utils/fuzzers/SchedulingPolicyServiceFuzz.cpp:57:32: note: in instantiation of function template specialization 'android::sp<android::IInterface>::sp<android::IBinder>' requested here
    requestCpusetBoost(enable, IInterface::asBinder(batteryStatService));
                               ^
1 error generated.
15:14:13 ninja failed with: exit status 1

#### failed to build some targets (26 seconds) ####
```

Patch-set: 11