Update patch set 9
Patch Set 9: Presubmit-Ready+1

just merged the change to take care of this prior build failure:
error: frameworks/av/media/extractors/tests/Android.bp:17:1: dependency "libstagefright_flacdec" of "ExtractorUnitTest" missing variant:

so we should be able to treehug with expectations of success....

Patch-set: 9
Reviewer: Gerrit User 1108919 <1108919@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1