Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > frameworks/av/media/libstagefright/tests/extractorFactory/ExtractorFactoryTest.cpp:92:32: error: no viable conversion from 'std::vector<std::string>' (aka 'vector<basic_string<char, char_traits<char>, allocator<char> > >') to 'unordered_set<std::string>' (aka 'unordered_set<basic_string<char, char_traits<char>, allocator<char> > >')
> >     unordered_set<std::string> supportedTypes = MediaExtractorFactory::getSupportedTypes();
> >                                ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > external/libcxx/include/unordered_set:465:5: note: candidate constructor not viable: no known conversion from 'std::vector<std::string>' (aka 'vector<basic_string<char, char_traits<char>, allocator<char> > >') to 'const std::__1::unordered_set<std::__1::basic_string<char>, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::basic_string<char> > > &' for 1st argument
> >     unordered_set(const unordered_set& __u);
> >     ^
> > external/libcxx/include/unordered_set:469:5: note: candidate constructor not viable: no known conversion from 'std::vector<std::string>' (aka 'vector<basic_string<char, char_traits<char>, allocator<char> > >') to 'std::__1::unordered_set<std::__1::basic_string<char>, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::basic_string<char> > > &&' for 1st argument
> >     unordered_set(unordered_set&& __u)
> >     ^
> > external/libcxx/include/unordered_set:472:5: note: candidate constructor not viable: no known conversion from 'std::vector<std::string>' (aka 'vector<basic_string<char, char_traits<char>, allocator<char> > >') to 'initializer_list<std::__1::unordered_set<std::__1::basic_string<char>, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::basic_string<char> > >::value_type>' (aka 'initializer_list<std::__1::basic_string<char> >') for 1st argument
> >     unordered_set(initializer_list<value_type> __il);
> >     ^
> > 1 error generated.
> 
> 
> 
> Ray,
> AOSP has the return data type as std::unordered_set<std::string> for getSupportedTypes() whereas RFS has it as std::vector<std::string>. Should I create a new CL for RFS or move this patch to RFS itself and abandon the current aosp patch?

Manisha,
let us check where this changed in r-fs-release and see how easy or difficult it is to cherry-pick that change to aosp/master.
if it requires too many CLs or if the CLs have any security fixes, then let us not cherry-pick them and we will decide next steps later.

Patch-set: 4
Reviewer: Gerrit User 1047003 <1047003@85c56323-6fa9-3386-8a01-6480fb634889>