Update patch set 4
Patch Set 4:

Presubmits are failing because it can't cherry-pick this change back to master:

error: could not apply de492e1... Add onExpirationUpdate and onKeyStatusChange listeners.

Would it be okay to mark this as DO NOT MERGE?

Patch-set: 4
Reviewer: Gerrit User 1344895 <1344895@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0