VolumeShaper: Parcelable should be initialized explicitly under Configuration
Without this, build fails on some old devices that use source that depends on VolumeShaper header file
e.g. bullhead
_
frameworks/av/include/media/VolumeShaper.h:135:18: error: base class 'class android::Parcelable' should be explicitly initialized in the copy constructor [-Werror=extra]
         explicit Configuration(const Configuration &configuration)
                  ^
-

Test: make hwcomposer.msm8992 -j8

Signed-off-by: argraur <argraur@gmail.com>