[Android Version]: Android8.1.0_r2
[CTS pachage version]
Suite / Plan	VTS / cts-on-gsi
Suite / Build	8.1_R3 / 4632653

[device](Any device config may relate this failure)
spreadtrum's iSharkL2
size:1080*1920

[bugzilla bugid] 78242092

[CTS Test Pre–Condition]
1.Language set to EN;
2.Keyguard set to none;
3.Enable GPS, Wifi network, USB debugging, Stay awake, Allow mock locations.
4.CTS version is VTS / cts-on-gsi 8.1_R3

[CTS Test Step]:
1 ./vts-tradefed
2 run cts-on-gsi

[Expected Result  ]:
This case will pass.

[Testing Result]:
case failed:
CtsCameraTestCases
--android.hardware.camera2.cts.RecordingTest#testBasicRecording
--android.hardware.camera2.cts.RecordingTest#testBurstVideoSnapshot
--android.hardware.camera2.cts.RecordingTest#testRecordingFramerateLowToHigh
--android.hardware.camera2.cts.RecordingTest#testRecordingFromPersistentSurface
--android.hardware.camera2.cts.RecordingTest#testSupportedVideoSizes
--android.hardware.camera2.cts.RecordingTest#testVideoSnapshot

junit.framework.AssertionFailedError: Cannot find video track! at android.hardware.camera2.cts.RecordingTest.validateRecording(RecordingTest.java:1406)

[Analysize]:
CTS case will set VideoSource to VIDEO_SOURCE_SURFACE, so Puller is NULL.
X86 platform will crash when doing mPuller->stopSource() in stopping process.

[Patch Link]:
https://android-review.googlesource.com/#/c/platform/cts/+/668521/