Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  frameworks/av/media/libmediaplayerservice/nuplayer/NuPlayer.cpp: In member function 'android::status_t android::NuPlayer::instantiateDecoder(bool, android::sp<android::NuPlayer::Decoder>*)':
frameworks/av/media/libmediaplayerservice/nuplayer/NuPlayer.cpp:819:25: error: 'struct android::NuPlayer::Source' has no member named 'isStreamValid'
In file included from frameworks/native/include/utils/RefBase.h:27:0,
                 from frameworks/av/include/media/MediaPlayerInterface.h:26,
                 from frameworks/av/media/libmediaplayerservice/nuplayer/NuPlayer.h:21,
                 from frameworks/av/media/libmediaplayerservice/nuplayer/NuPlayer.cpp:21:
frameworks/native/include/utils/StrongPointer.h: In instantiation of 'android::sp<T>::sp(const android::sp<U>&) [with U = android::AMessage; T = android::MetaData]':
frameworks/av/media/libmediaplayerservice/nuplayer/NuPlayer.cpp:820:54:   required from here
frameworks/native/include/utils/StrongPointer.h:141:20: error: cannot convert 'android::AMessage* const' to 'android::MetaData*' in initialization
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Reviewer: Gerrit User 1006433 <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1